### ISSUE TITLE
Impossible to complete all the actions to install boolexpr [http://www.boolexpr.org/] 

### ISSUE THREAD

**Issue by kregus0** [cjdrake/boolexpr#25]
Subject : Impossible to complete all the actions to install boolexpr [http://www.boolexpr.org/] 

### Problem
- I am trying to install boolexpr (boolexpr.org) on my laptop Intel Atom CPU running in amd64. Following line per line the README.rst at the time of executing make pyhtml which is the last line of Build Documentation after typing pip install sphinx on the command line I get an « Exception occurred » in the middle of the execution.

I already posted this message in issues sphinx, but the problem most likely comes from boolexpr.
Yesterday, I tried with python2.
The current attempt results from a modification of the install scrypt to call python3.

My OS version : Ubuntu 15.04.

#### Procedure to reproduce the problem
Path command line :
In /home/kevin/download/boolexpr/build
Command line : 
make pyhtml

#### Error logs / results
```
kevin@caspian:~/boolexpr/build$ make pyhtml
[...]
copying build/lib.linux-x86_64-2.7/boolexpr/_boolexpr.so -> boolexpr
running build_sphinx
creating /home/kevin/boolexpr/build/python/build/sphinx
creating /home/kevin/boolexpr/build/python/build/sphinx/doctrees
creating /home/kevin/boolexpr/build/python/build/sphinx/html
Running Sphinx v1.6.2

Exception occurred:
  File "/home/kevin/boolexpr/build/python/boolexpr/__init__.py", line 65, in <module>
    import importlib.util
ImportError: No module named util
The full traceback has been saved in /tmp/sphinx-err-7KQ4_h.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
python/CMakeFiles/pyhtml.dir/build.make:49: recipe for target 'python/CMakeFiles/pyhtml' failed
make[3]: *** [python/CMakeFiles/pyhtml] Error 1
CMakeFiles/Makefile2:176: recipe for target 'python/CMakeFiles/pyhtml.dir/all' failed
make[2]: *** [python/CMakeFiles/pyhtml.dir/all] Error 2
CMakeFiles/Makefile2:184: recipe for target 'python/CMakeFiles/pyhtml.dir/rule' failed
make[1]: *** [python/CMakeFiles/pyhtml.dir/rule] Error 2
Makefile:188: recipe for target 'pyhtml' failed
make: *** [pyhtml] Error 2
```

The content of the file mentionned above is present below : 
```
# Sphinx version: 1.6.2
# Python version: 2.7.9 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/kevin/.local/lib/python2.7/site-packages/sphinx/setup_command.py", line 191, in run
    warningiserror=self.warning_is_error)
  File "/home/kevin/.local/lib/python2.7/site-packages/sphinx/application.py", line 168, in __init__
    confoverrides or {}, self.tags)
  File "/home/kevin/.local/lib/python2.7/site-packages/sphinx/config.py", line 150, in __init__
    execfile_(filename, config)
  File "/home/kevin/.local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/kevin/.local/lib/python2.7/site-packages/six.py", line 699, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 24, in <module>
  File "/home/kevin/boolexpr/build/python/boolexpr/__init__.py", line 65, in <module>
    import importlib.util
ImportError: No module named util
```

### Environment info
- OS: Ubuntu 15.04 this is the output of /etc/issue
- Python version: 2.7.9 this is the output of python -V
- Sphinx version: 2.0.4 –id64-release (r3135) this is the output of searchd --help

[error_log_with_python_2.txt](https://github.com/cjdrake/boolexpr/files/1103533/error_log_with_python_2.txt)
[error_log_with_python3.txt](https://github.com/cjdrake/boolexpr/files/1103535/error_log_with_python3.txt)

**Comment by cjdrake** [comment]
I'm not currently supporting Python2.*

In the `error_log_with_python3.txt` file, it says "Python version: 2.7.9 (CPython)".

The problem comes from this section in `boolexpr/__init.py.in`:

```python
ffi = cffi.FFI()
ffi.cdef(HEADER)
_libpath = importlib.util.find_spec("boolexpr._boolexpr").origin
lib = ffi.dlopen(_libpath)
```

In Python 2.*, importlib does not have a `util` module.

Pretty sure you are seeing the same thing as issue #21.
