### ISSUE TITLE
Using boolexpr

### ISSUE THREAD

**Issue by adelin-b** [cjdrake/boolexpr#26]
Salutations,
I fail at using boolexpr :(.
Could you please provide a working compiling line that don't get any error or undefined reference?
here is what I got but there is an undefined reference.

`cd boolexpr`
`g++ -std=c++11 -Wall   -g -lm -L build/libboolexpr.a   -I third_party/boost-1.54.0/  -I third_party/glucosamine/src/  -I. -I include/boolexpr/ example.c`

here is the example.c :
`#include <stdbool.h>
#include <boolexpr.h>

int	 main(void)
	{
	void *ctx;

	ctx = boolexpr_Context_new();
	
	return (0);
	}
` 

I get an undefined reference to bool_expr_Context_new

**Comment by cjdrake** [comment]
I got the same thing when I tried it. I don't understand the issue yet.

**Comment by cjdrake** [comment]
Okay, I think I got it. Looks like you're using the `-L` argument incorrectly. Try this instead:

```
g++ -std=c++11 -o example -Iinclude -Ithird_party/boost-1.54.0 -I third_party/glucosamine/src -Lbuild example.c -lboolexpr
```
