### ISSUE TITLE
Using C++ API to initialize a boolean variable/expression to value 0 or 1

### ISSUE THREAD

**Issue by acoader** [cjdrake/boolexpr#30]
Hello cjdrake,
I'm trying to use the C++ API. Are there any examples out there to show c++ API usage?

To start off I wanted to create a variable and assign it a 0 or 1 value, something like:
Variable x = One; or perhaps
var_t x = One;
Above is possible using python API. How do we do it in C++?
Thank you.

**Comment by cjdrake** [comment]
The package has some CMake files, so hopefully it's not too hard to get the build going. As for examples, I would look at unit test code for basic usage. For example, [these](https://github.com/cjdrake/boolexpr/blob/master/test/boolexprtest.h) [three](https://github.com/cjdrake/boolexpr/blob/master/test/boolexprtest.cc) [files](https://github.com/cjdrake/boolexpr/blob/master/test/basic_test.cc) should be useful.

Beyond that, I haven't had much time to look at open source lately. I suspect there is some cruft that has accumulated, and would be glad to have help keeping things up-to-date.

**Comment by acoader** [comment]
Thanks. Let me look around the unit test code .  I could not locate what I was looking for in my first search .. 
perhaps var_t x = one(); 
I had tried a bunch of syntaxes but got errors. 

Regarding makefile, yes thanks I found a static library got built that  I was able to link with . I couldn’t find a .so file however. Is the makefile set up to make a shared library ?

**Comment by acoader** [comment]
Basic question - where are xs[0] etc defined? It's probably a dumb question - If I use a proper IDE or grep I should be able to locate it - it seems a bit tricky

**Comment by acoader** [comment]
Ok, I do see xs in boolexprtest.h:
class BoolExprTest : public ::testing::Test
{
...
    vector<var_t> xs;
....
};
But not sure above is the same xs as the one used bare in basic_test.cc:
EXPECT_EQ(ctx.get_var("x_0"), xs[0]);

**Comment by acoader** [comment]
Closing this as I have figured this out. Thank you!
