### ISSUE TITLE
ESPRESSO?

### ISSUE THREAD

**Issue by wasabii** [cjdrake/boolexpr#35]
Do you plan to implement ESPRESSO in this library much as you did in PyEDA?

**Comment by cjdrake** [comment]
Well I'm not working on any features at the moment, just tinkering around with things in this field. That said, it would be an interesting trick to implement Espresso for this library. Espresso requires a DNF, and it's non-trivial to produce one.

**Comment by wasabii** [comment]
Heh. I'm doing a bunch of work with this library, with the end goal of feeding it into ESPRESSO. Wrote some .NET wrappers.

Your last sentence has me worried. Doesn't this library produce a DNF?

Yeah, `boolexpr_BoolExpr_to_dnf`.
